#ifndef FFDUP_BUILD_CONSTANTS_H
#define FFDUP_BUILD_CONSTANTS_H

#define HASHTABLE_BUCKETS  1024
#define FILENAME_COMPONENT_LEN 255
#define MAX_TRACKED_DUPLICATES 128
#define MAX_DIRECTORY_DEPTH 64
#define FILESIZES_PER_HASHTABLE_NODE 16

#endif // FFDUP_BUILD_CONSTANTS_H
